name: "Bug report"
description: "Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord."
title: "[BUG]"
body:
  - type: textarea
    id: Describe-the-bug
    attributes:
      value: Describe the bug
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      value: Steps to reproduce
      description: |
        What do we need to do after opening your repro in order to make the bug happen? Clear and concise reproduction instructions are important for us to be able to triage your issue in a timely manner. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format lists and code.
      placeholder: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      value: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actually-happening
    attributes:
      value: What is actually happening?
    validations:
      required: true
  - type: markdown
    id: Screenshots
    attributes:
      value: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: additional-comments
    attributes:
      value: Any additional comments?
      description: e.g. some background/context of how you ran into this bug.
